/**
 * @file feb_can.c
 *
 * @brief This source file was generated by cantools version 40.2.1 Sun Mar  9 16:46:07 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <FEB_CAN.h>
#include <string.h>


static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t unpack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) << shift);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int feb_can_feb_bms_cell_voltage_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_bms_cell_voltage_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->bank_number, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->cell_number, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->cell_voltage, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->cell_voltage, 8u, 0xffu);

    return (4);
}

int feb_can_feb_bms_cell_voltage_unpack(
    struct feb_can_feb_bms_cell_voltage_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->bank_number = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->cell_number = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->cell_voltage = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->cell_voltage |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

int feb_can_feb_bms_cell_voltage_init(struct feb_can_feb_bms_cell_voltage_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct feb_can_feb_bms_cell_voltage_t));

    return 0;
}

uint8_t feb_can_feb_bms_cell_voltage_bank_number_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_feb_bms_cell_voltage_bank_number_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_feb_bms_cell_voltage_bank_number_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t feb_can_feb_bms_cell_voltage_cell_number_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_feb_bms_cell_voltage_cell_number_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_feb_bms_cell_voltage_cell_number_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t feb_can_feb_bms_cell_voltage_cell_voltage_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double feb_can_feb_bms_cell_voltage_cell_voltage_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool feb_can_feb_bms_cell_voltage_cell_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int feb_can_feb_iv_meter_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_iv_meter_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_right_shift_u8(src_p->low_range_current, 7u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->low_range_current, 1u, 0xfeu);
    dst_p[1] |= pack_right_shift_u8(src_p->high_range_current, 7u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->high_range_current, 1u, 0xfeu);
    dst_p[2] |= pack_right_shift_u8(src_p->hv_voltage, 7u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->hv_voltage, 1u, 0xfeu);

    return (4);
}

int feb_can_feb_iv_meter_unpack(
    struct feb_can_feb_iv_meter_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->low_range_current = unpack_left_shift_u8(src_p[0], 7u, 0x01u);
    dst_p->low_range_current |= unpack_right_shift_u8(src_p[1], 1u, 0xfeu);
    dst_p->high_range_current = unpack_left_shift_u8(src_p[1], 7u, 0x01u);
    dst_p->high_range_current |= unpack_right_shift_u8(src_p[2], 1u, 0xfeu);
    dst_p->hv_voltage = unpack_left_shift_u8(src_p[2], 7u, 0x01u);
    dst_p->hv_voltage |= unpack_right_shift_u8(src_p[3], 1u, 0xfeu);

    return (0);
}

int feb_can_feb_iv_meter_init(struct feb_can_feb_iv_meter_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct feb_can_feb_iv_meter_t));

    return 0;
}

uint8_t feb_can_feb_iv_meter_low_range_current_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_feb_iv_meter_low_range_current_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_feb_iv_meter_low_range_current_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t feb_can_feb_iv_meter_high_range_current_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_feb_iv_meter_high_range_current_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_feb_iv_meter_high_range_current_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t feb_can_feb_iv_meter_hv_voltage_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_feb_iv_meter_hv_voltage_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_feb_iv_meter_hv_voltage_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int feb_can_feb_lvpdb_flags_bus_voltage_lv_current_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_lvpdb_flags_bus_voltage_lv_current_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->flags, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->flags, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->flags, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->flags, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->bus_voltage, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->bus_voltage, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->lv_current, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->lv_current, 8u, 0xffu);

    return (8);
}

int feb_can_feb_lvpdb_flags_bus_voltage_lv_current_unpack(
    struct feb_can_feb_lvpdb_flags_bus_voltage_lv_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->flags = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->flags |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->flags |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->flags |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->bus_voltage = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->bus_voltage |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->lv_current = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->lv_current |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int feb_can_feb_lvpdb_flags_bus_voltage_lv_current_init(struct feb_can_feb_lvpdb_flags_bus_voltage_lv_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct feb_can_feb_lvpdb_flags_bus_voltage_lv_current_t));

    return 0;
}

uint32_t feb_can_feb_lvpdb_flags_bus_voltage_lv_current_flags_encode(double value)
{
    return (uint32_t)(value);
}

double feb_can_feb_lvpdb_flags_bus_voltage_lv_current_flags_decode(uint32_t value)
{
    return ((double)value);
}

bool feb_can_feb_lvpdb_flags_bus_voltage_lv_current_flags_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint16_t feb_can_feb_lvpdb_flags_bus_voltage_lv_current_bus_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double feb_can_feb_lvpdb_flags_bus_voltage_lv_current_bus_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool feb_can_feb_lvpdb_flags_bus_voltage_lv_current_bus_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t feb_can_feb_lvpdb_flags_bus_voltage_lv_current_lv_current_encode(double value)
{
    return (uint16_t)(value);
}

double feb_can_feb_lvpdb_flags_bus_voltage_lv_current_lv_current_decode(uint16_t value)
{
    return ((double)value);
}

bool feb_can_feb_lvpdb_flags_bus_voltage_lv_current_lv_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int feb_can_feb_lvpdb_cp_af_rf_sh_current_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_lvpdb_cp_af_rf_sh_current_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->cp_current, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->cp_current, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->af_current, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->af_current, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->rf_current, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->rf_current, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->sh_voltage, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->sh_voltage, 8u, 0xffu);

    return (8);
}

int feb_can_feb_lvpdb_cp_af_rf_sh_current_unpack(
    struct feb_can_feb_lvpdb_cp_af_rf_sh_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cp_current = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->cp_current |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->af_current = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->af_current |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->rf_current = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->rf_current |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->sh_voltage = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->sh_voltage |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int feb_can_feb_lvpdb_cp_af_rf_sh_current_init(struct feb_can_feb_lvpdb_cp_af_rf_sh_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct feb_can_feb_lvpdb_cp_af_rf_sh_current_t));

    return 0;
}

uint16_t feb_can_feb_lvpdb_cp_af_rf_sh_current_cp_current_encode(double value)
{
    return (uint16_t)(value);
}

double feb_can_feb_lvpdb_cp_af_rf_sh_current_cp_current_decode(uint16_t value)
{
    return ((double)value);
}

bool feb_can_feb_lvpdb_cp_af_rf_sh_current_cp_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t feb_can_feb_lvpdb_cp_af_rf_sh_current_af_current_encode(double value)
{
    return (uint16_t)(value);
}

double feb_can_feb_lvpdb_cp_af_rf_sh_current_af_current_decode(uint16_t value)
{
    return ((double)value);
}

bool feb_can_feb_lvpdb_cp_af_rf_sh_current_af_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t feb_can_feb_lvpdb_cp_af_rf_sh_current_rf_current_encode(double value)
{
    return (uint16_t)(value);
}

double feb_can_feb_lvpdb_cp_af_rf_sh_current_rf_current_decode(uint16_t value)
{
    return ((double)value);
}

bool feb_can_feb_lvpdb_cp_af_rf_sh_current_rf_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t feb_can_feb_lvpdb_cp_af_rf_sh_current_sh_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double feb_can_feb_lvpdb_cp_af_rf_sh_current_sh_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool feb_can_feb_lvpdb_cp_af_rf_sh_current_sh_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int feb_can_feb_lvpdb_l_as_ab_current_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_lvpdb_l_as_ab_current_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->l_current, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->l_current, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->as_voltage, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->as_voltage, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->ab_voltage, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->ab_voltage, 8u, 0xffu);

    return (8);
}

int feb_can_feb_lvpdb_l_as_ab_current_unpack(
    struct feb_can_feb_lvpdb_l_as_ab_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->l_current = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->l_current |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->as_voltage = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->as_voltage |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->ab_voltage = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->ab_voltage |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int feb_can_feb_lvpdb_l_as_ab_current_init(struct feb_can_feb_lvpdb_l_as_ab_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct feb_can_feb_lvpdb_l_as_ab_current_t));

    return 0;
}

uint16_t feb_can_feb_lvpdb_l_as_ab_current_l_current_encode(double value)
{
    return (uint16_t)(value);
}

double feb_can_feb_lvpdb_l_as_ab_current_l_current_decode(uint16_t value)
{
    return ((double)value);
}

bool feb_can_feb_lvpdb_l_as_ab_current_l_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t feb_can_feb_lvpdb_l_as_ab_current_as_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double feb_can_feb_lvpdb_l_as_ab_current_as_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool feb_can_feb_lvpdb_l_as_ab_current_as_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t feb_can_feb_lvpdb_l_as_ab_current_ab_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double feb_can_feb_lvpdb_l_as_ab_current_ab_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool feb_can_feb_lvpdb_l_as_ab_current_ab_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int feb_can_normalized_brake_pack(
    uint8_t *dst_p,
    const struct feb_can_normalized_brake_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u64(src_p->normalized_break, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->normalized_break, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->normalized_break, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->normalized_break, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->normalized_break, 32u, 0xffu);

    return (5);
}

int feb_can_normalized_brake_unpack(
    struct feb_can_normalized_brake_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->normalized_break = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    dst_p->normalized_break |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    dst_p->normalized_break |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    dst_p->normalized_break |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->normalized_break |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);

    return (0);
}

int feb_can_normalized_brake_init(struct feb_can_normalized_brake_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct feb_can_normalized_brake_t));

    return 0;
}

uint64_t feb_can_normalized_brake_normalized_break_encode(double value)
{
    return (uint64_t)(value);
}

double feb_can_normalized_brake_normalized_break_decode(uint64_t value)
{
    return ((double)value);
}

bool feb_can_normalized_brake_normalized_break_is_in_range(uint64_t value)
{
    return (value <= 1099511627775ull);
}

int feb_can_rms_param_msg_pack(
    uint8_t *dst_p,
    const struct feb_can_rms_param_msg_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u8(src_p->addr, 7u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->addr, 1u, 0xfeu);
    dst_p[2] |= pack_right_shift_u8(src_p->read_write_command, 7u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->read_write_command, 1u, 0xfeu);
    dst_p[3] |= pack_right_shift_u16(src_p->data, 15u, 0x01u);
    dst_p[4] |= pack_right_shift_u16(src_p->data, 7u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->data, 1u, 0xfeu);

    return (8);
}

int feb_can_rms_param_msg_unpack(
    struct feb_can_rms_param_msg_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->addr = unpack_left_shift_u8(src_p[0], 7u, 0x01u);
    dst_p->addr |= unpack_right_shift_u8(src_p[1], 1u, 0xfeu);
    dst_p->read_write_command = unpack_left_shift_u8(src_p[2], 7u, 0x01u);
    dst_p->read_write_command |= unpack_right_shift_u8(src_p[3], 1u, 0xfeu);
    dst_p->data = unpack_left_shift_u16(src_p[3], 15u, 0x01u);
    dst_p->data |= unpack_left_shift_u16(src_p[4], 7u, 0xffu);
    dst_p->data |= unpack_right_shift_u16(src_p[5], 1u, 0xfeu);

    return (0);
}

int feb_can_rms_param_msg_init(struct feb_can_rms_param_msg_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct feb_can_rms_param_msg_t));

    return 0;
}

uint8_t feb_can_rms_param_msg_addr_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_rms_param_msg_addr_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_rms_param_msg_addr_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t feb_can_rms_param_msg_read_write_command_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_rms_param_msg_read_write_command_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_rms_param_msg_read_write_command_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t feb_can_rms_param_msg_data_encode(double value)
{
    return (uint16_t)(value);
}

double feb_can_rms_param_msg_data_decode(uint16_t value)
{
    return ((double)value);
}

bool feb_can_rms_param_msg_data_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int feb_can_rms_command_msg_pack(
    uint8_t *dst_p,
    const struct feb_can_rms_command_msg_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->torque_signal, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->torque_signal, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->speed_signal, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->speed_signal, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->direction_value, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->inverter_enable, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->command_torque_limited, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->command_torque_limited, 8u, 0xffu);

    return (8);
}

int feb_can_rms_command_msg_unpack(
    struct feb_can_rms_command_msg_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->torque_signal = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->torque_signal |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->speed_signal = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->speed_signal |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->direction_value = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->inverter_enable = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->command_torque_limited = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->command_torque_limited |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int feb_can_rms_command_msg_init(struct feb_can_rms_command_msg_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct feb_can_rms_command_msg_t));

    return 0;
}

uint16_t feb_can_rms_command_msg_torque_signal_encode(double value)
{
    return (uint16_t)(value);
}

double feb_can_rms_command_msg_torque_signal_decode(uint16_t value)
{
    return ((double)value);
}

bool feb_can_rms_command_msg_torque_signal_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t feb_can_rms_command_msg_speed_signal_encode(double value)
{
    return (uint16_t)(value);
}

double feb_can_rms_command_msg_speed_signal_decode(uint16_t value)
{
    return ((double)value);
}

bool feb_can_rms_command_msg_speed_signal_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t feb_can_rms_command_msg_direction_value_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_rms_command_msg_direction_value_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_rms_command_msg_direction_value_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t feb_can_rms_command_msg_inverter_enable_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_rms_command_msg_inverter_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_rms_command_msg_inverter_enable_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t feb_can_rms_command_msg_command_torque_limited_encode(double value)
{
    return (uint16_t)(value);
}

double feb_can_rms_command_msg_command_torque_limited_decode(uint16_t value)
{
    return ((double)value);
}

bool feb_can_rms_command_msg_command_torque_limited_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int feb_can_bspd_pack(
    uint8_t *dst_p,
    const struct feb_can_bspd_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->bspd_state, 0u, 0xffu);

    return (1);
}

int feb_can_bspd_unpack(
    struct feb_can_bspd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->bspd_state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int feb_can_bspd_init(struct feb_can_bspd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct feb_can_bspd_t));

    return 0;
}

uint8_t feb_can_bspd_bspd_state_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_bspd_bspd_state_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_bspd_bspd_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int feb_can_tps_current_pack(
    uint8_t *dst_p,
    const struct feb_can_tps_current_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u64(src_p->current, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->current, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->current, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->current, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->current, 32u, 0xffu);

    return (5);
}

int feb_can_tps_current_unpack(
    struct feb_can_tps_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->current = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    dst_p->current |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    dst_p->current |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    dst_p->current |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->current |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);

    return (0);
}

int feb_can_tps_current_init(struct feb_can_tps_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct feb_can_tps_current_t));

    return 0;
}

uint64_t feb_can_tps_current_current_encode(double value)
{
    return (uint64_t)(value);
}

double feb_can_tps_current_current_decode(uint64_t value)
{
    return ((double)value);
}

bool feb_can_tps_current_current_is_in_range(uint64_t value)
{
    return (value <= 1099511627775ull);
}

int feb_can_feb_dash_message_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_dash_message_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->buzzer_state, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->button1_ready_to_drive, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->button2, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->button3, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->button4, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->coolant_pump_switch, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->radiator_fan_switch, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->accumulator_fan_switch, 7u, 0x80u);

    return (1);
}

int feb_can_feb_dash_message_unpack(
    struct feb_can_feb_dash_message_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->buzzer_state = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->button1_ready_to_drive = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->button2 = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->button3 = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->button4 = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->coolant_pump_switch = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->radiator_fan_switch = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->accumulator_fan_switch = unpack_right_shift_u8(src_p[0], 7u, 0x80u);

    return (0);
}

int feb_can_feb_dash_message_init(struct feb_can_feb_dash_message_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct feb_can_feb_dash_message_t));

    return 0;
}

uint8_t feb_can_feb_dash_message_buzzer_state_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_feb_dash_message_buzzer_state_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_feb_dash_message_buzzer_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t feb_can_feb_dash_message_button1_ready_to_drive_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_feb_dash_message_button1_ready_to_drive_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_feb_dash_message_button1_ready_to_drive_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t feb_can_feb_dash_message_button2_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_feb_dash_message_button2_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_feb_dash_message_button2_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t feb_can_feb_dash_message_button3_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_feb_dash_message_button3_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_feb_dash_message_button3_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t feb_can_feb_dash_message_button4_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_feb_dash_message_button4_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_feb_dash_message_button4_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t feb_can_feb_dash_message_coolant_pump_switch_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_feb_dash_message_coolant_pump_switch_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_feb_dash_message_coolant_pump_switch_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t feb_can_feb_dash_message_radiator_fan_switch_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_feb_dash_message_radiator_fan_switch_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_feb_dash_message_radiator_fan_switch_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t feb_can_feb_dash_message_accumulator_fan_switch_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_feb_dash_message_accumulator_fan_switch_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_feb_dash_message_accumulator_fan_switch_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int feb_can_feb_dart_tach_measurements_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_dart_tach_measurements_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->fan1_speed, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->fan2_speed, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->fan3_speed, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->fan4_speed, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->fan5_speed, 0u, 0xffu);

    return (5);
}

int feb_can_feb_dart_tach_measurements_unpack(
    struct feb_can_feb_dart_tach_measurements_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->fan1_speed = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->fan2_speed = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->fan3_speed = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->fan4_speed = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->fan5_speed = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int feb_can_feb_dart_tach_measurements_init(struct feb_can_feb_dart_tach_measurements_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct feb_can_feb_dart_tach_measurements_t));

    return 0;
}

uint8_t feb_can_feb_dart_tach_measurements_fan1_speed_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_feb_dart_tach_measurements_fan1_speed_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_feb_dart_tach_measurements_fan1_speed_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t feb_can_feb_dart_tach_measurements_fan2_speed_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_feb_dart_tach_measurements_fan2_speed_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_feb_dart_tach_measurements_fan2_speed_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t feb_can_feb_dart_tach_measurements_fan3_speed_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_feb_dart_tach_measurements_fan3_speed_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_feb_dart_tach_measurements_fan3_speed_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t feb_can_feb_dart_tach_measurements_fan4_speed_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_feb_dart_tach_measurements_fan4_speed_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_feb_dart_tach_measurements_fan4_speed_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t feb_can_feb_dart_tach_measurements_fan5_speed_encode(double value)
{
    return (uint8_t)(value);
}

double feb_can_feb_dart_tach_measurements_fan5_speed_decode(uint8_t value)
{
    return ((double)value);
}

bool feb_can_feb_dart_tach_measurements_fan5_speed_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int feb_can_feb_ping_pong_counter1_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_ping_pong_counter1_t *src_p,
    size_t size)
{
    uint32_t counter;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    counter = (uint32_t)src_p->counter;
    dst_p[0] |= pack_left_shift_u32(counter, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(counter, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(counter, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(counter, 24u, 0xffu);

    return (8);
}

int feb_can_feb_ping_pong_counter1_unpack(
    struct feb_can_feb_ping_pong_counter1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t counter;

    if (size < 8u) {
        return (-EINVAL);
    }

    counter = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    counter |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    counter |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    counter |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->counter = (int32_t)counter;

    return (0);
}

int feb_can_feb_ping_pong_counter1_init(struct feb_can_feb_ping_pong_counter1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct feb_can_feb_ping_pong_counter1_t));

    return 0;
}

int32_t feb_can_feb_ping_pong_counter1_counter_encode(double value)
{
    return (int32_t)(value);
}

double feb_can_feb_ping_pong_counter1_counter_decode(int32_t value)
{
    return ((double)value);
}

bool feb_can_feb_ping_pong_counter1_counter_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int feb_can_feb_ping_pong_counter2_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_ping_pong_counter2_t *src_p,
    size_t size)
{
    uint32_t counter;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    counter = (uint32_t)src_p->counter;
    dst_p[0] |= pack_left_shift_u32(counter, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(counter, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(counter, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(counter, 24u, 0xffu);

    return (8);
}

int feb_can_feb_ping_pong_counter2_unpack(
    struct feb_can_feb_ping_pong_counter2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t counter;

    if (size < 8u) {
        return (-EINVAL);
    }

    counter = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    counter |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    counter |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    counter |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->counter = (int32_t)counter;

    return (0);
}

int feb_can_feb_ping_pong_counter2_init(struct feb_can_feb_ping_pong_counter2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct feb_can_feb_ping_pong_counter2_t));

    return 0;
}

int32_t feb_can_feb_ping_pong_counter2_counter_encode(double value)
{
    return (int32_t)(value);
}

double feb_can_feb_ping_pong_counter2_counter_decode(int32_t value)
{
    return ((double)value);
}

bool feb_can_feb_ping_pong_counter2_counter_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int feb_can_feb_ping_pong_counter3_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_ping_pong_counter3_t *src_p,
    size_t size)
{
    uint32_t counter;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    counter = (uint32_t)src_p->counter;
    dst_p[0] |= pack_left_shift_u32(counter, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(counter, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(counter, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(counter, 24u, 0xffu);

    return (8);
}

int feb_can_feb_ping_pong_counter3_unpack(
    struct feb_can_feb_ping_pong_counter3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t counter;

    if (size < 8u) {
        return (-EINVAL);
    }

    counter = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    counter |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    counter |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    counter |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->counter = (int32_t)counter;

    return (0);
}

int feb_can_feb_ping_pong_counter3_init(struct feb_can_feb_ping_pong_counter3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct feb_can_feb_ping_pong_counter3_t));

    return 0;
}

int32_t feb_can_feb_ping_pong_counter3_counter_encode(double value)
{
    return (int32_t)(value);
}

double feb_can_feb_ping_pong_counter3_counter_decode(int32_t value)
{
    return ((double)value);
}

bool feb_can_feb_ping_pong_counter3_counter_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int feb_can_feb_ping_pong_counter4_pack(
    uint8_t *dst_p,
    const struct feb_can_feb_ping_pong_counter4_t *src_p,
    size_t size)
{
    uint32_t counter;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    counter = (uint32_t)src_p->counter;
    dst_p[0] |= pack_left_shift_u32(counter, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(counter, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(counter, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(counter, 24u, 0xffu);

    return (8);
}

int feb_can_feb_ping_pong_counter4_unpack(
    struct feb_can_feb_ping_pong_counter4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t counter;

    if (size < 8u) {
        return (-EINVAL);
    }

    counter = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    counter |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    counter |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    counter |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->counter = (int32_t)counter;

    return (0);
}

int feb_can_feb_ping_pong_counter4_init(struct feb_can_feb_ping_pong_counter4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct feb_can_feb_ping_pong_counter4_t));

    return 0;
}

int32_t feb_can_feb_ping_pong_counter4_counter_encode(double value)
{
    return (int32_t)(value);
}

double feb_can_feb_ping_pong_counter4_counter_decode(int32_t value)
{
    return ((double)value);
}

bool feb_can_feb_ping_pong_counter4_counter_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}
